title: "Bartu's Blog"
author: "Bartu Baş"
description: "Stuff from here and there" # This will show up in places like twitter, linkedin, etc, if you share your sites url as a post.

# Email / Social media user names used by the minima theme:
# All of these are optional and can be removed or commented out
email: "bartubas99@gmail.com"
#twitter_username: "twitteruser"
github_username: "vectorized-runner"
linkedin_username: "bartubas"
gitlab_username: "vectorized_runner"

#facebook_username: username
#flickr_username: username
#instagram_username: username
#pinterest_username: username
#youtube_username: username
#googleplus_username: +username

lsi: false
safe: true
incremental: false
highlighter: rouge
gist:
  noscript: false
  
# Jekyll 3 now only supports Kramdown for Markdown
kramdown:
    math_engine: mathjax
    # Use GitHub flavored markdown, including triple backtick fenced code blocks
    input: GFM
    # Jekyll 3 and GitHub Pages now only support rouge for syntax highlighting
    syntax_highlighter: rouge
    syntax_highlighter_opts:
    # Use existing pygments syntax highlighting css
    css_class: 'highlight'


theme: "minima"

rss: rss
    
plugins:
  - jekyll-feed
  - jekyll-sitemap

titles_from_headings:
  strip_title: true
  collections: true

defaults:
  - scope:
      path: ""
      type: post
    values:
      tags: Other
